version: "3.7"
services:
  modem-tunnel:
    image: cloudflare/cloudflared
    user: root
    container_name: modem-tunnel
    volumes:
      - $HOME/.cloudflared:/.cloudflared
    restart: unless-stopped
    command: ["tunnel", "--hostname", "modem.ewqiop.com", "--url", "http://192.168.1.1", "--origincert", "/.cloudflared/cert.pem", "--no-autoupdate"]